# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anniversary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_date', models.CharField(help_text='생일날자', max_length=20, verbose_name='생일날자')),
                ('anniversary_name', models.CharField(default='', help_text='생일 당사자 이름', max_length=20, verbose_name='이름')),
                ('anniversary_lunar_date', models.CharField(blank=True, help_text='생일 음력 날자', max_length=20, verbose_name='생일 음력 날자')),
                ('daily_created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='생성날자', verbose_name='생성일')),
                ('daily_published_date', models.DateTimeField(auto_now=True, help_text='수정날자', verbose_name='수정일')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_date', models.DateField(help_text='날자입력', verbose_name='날자')),
                ('daily_day', models.CharField(help_text='토요일 입력', max_length=4, verbose_name='요일')),
                ('daily_content', models.TextField(help_text='summernote 글 내용', verbose_name='글내용')),
                ('daily_created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='생성날자', verbose_name='생성일')),
                ('daily_published_date', models.DateTimeField(auto_now=True, help_text='수정날자', verbose_name='수정일')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='GwBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwbank_name_choices', models.CharField(blank=True, choices=[('이채순', '이채순'), ('이기창', '이기창'), ('이화순', '이화순')], help_text='이름으로 특정 데이터 가져오기', max_length=4, verbose_name='이름으로 구분')),
                ('gwbank_date', models.DateField(help_text='입출금 날자', verbose_name='날자')),
                ('gwbank_income', models.CharField(help_text='입금 출륵 중 선택', max_length=5, verbose_name='입금출금')),
                ('gwbank_money', models.PositiveIntegerField(help_text='입출금 금액', verbose_name='금액')),
                ('gwbank_name', models.CharField(blank=True, help_text='이름 및 설명글 작성', max_length=20, verbose_name='이름 및 설명글')),
                ('gwbank_execution', models.PositiveIntegerField(blank=True, default=0, help_text='특정 값 합계 금액 적는 필드', verbose_name='특정 값 합계 금액 정수')),
                ('gwbank_note', models.CharField(blank=True, default='', help_text='메모 필드', max_length=200, verbose_name='메모')),
                ('daily_created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='생성날자', verbose_name='생성일')),
                ('daily_published_date', models.DateTimeField(auto_now=True, help_text='수정날자', verbose_name='수정일')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(help_text='  ', max_length=200, verbose_name='제목')),
                ('note_content', models.TextField(verbose_name='내용 (사진 사이즈가 크면 등록되지 않습니다!)')),
                ('note_created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='생성 날자', verbose_name='생성일')),
                ('note_published_date', models.DateTimeField(auto_now=True, help_text='글 수정 일시', null=True, verbose_name='수정일')),
                ('note_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NoteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notecomment_content', models.TextField(verbose_name='글내용')),
                ('notecomment_created_date', models.DateTimeField(auto_now_add=True, help_text='생성날자', verbose_name='생성날자')),
                ('notecomment_publish_date', models.DateTimeField(auto_now=True, help_text='수정날자', verbose_name='수정날자')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='family_site.Note')),
                ('notecomment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-notecomment_created_date',),
            },
        ),
        migrations.CreateModel(
            name='WrBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrbank_date', models.DateField(help_text='날자를 표기', verbose_name='날자')),
                ('wrbank_deposit_withdrawal', models.CharField(help_text='입금 출금 표기', max_length=10, verbose_name='입출금')),
                ('wrbank_money1', models.PositiveIntegerField(blank=True, default=0, help_text='금액, 이자를 표기', verbose_name='금액')),
                ('wrbank_note', models.CharField(default='', help_text='비고 및 설명글 표기', max_length=200, verbose_name='비고 및 설명글')),
                ('wrbank_money2', models.PositiveIntegerField(blank=True, default=0, help_text='대출 이자를 표기', verbose_name='대출이자')),
                ('wrbank_money3', models.PositiveIntegerField(blank=True, default=0, help_text='원금을 표기', verbose_name='원금')),
                ('wrbank_aggregate', models.PositiveIntegerField(blank=True, default=0, help_text='이자와 원금 합계', verbose_name='합계')),
                ('wrbank_loan_balance', models.PositiveIntegerField(blank=True, default=75000000, help_text='대출잔액', verbose_name='대출잔액')),
                ('wrbank_bankbook_balance', models.PositiveIntegerField(default=0, help_text='통장 잔액', verbose_name='통장잔액')),
                ('daily_created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='생성날자', verbose_name='생성일')),
                ('daily_published_date', models.DateTimeField(auto_now=True, help_text='수정날자', verbose_name='수정일')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
