# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anniversary',
            name='anniversary_day',
            field=models.CharField(default='', help_text='요일', max_length=10, verbose_name='요일'),
        ),
    ]
