# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_site', '0002_anniversary_anniversary_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwbank',
            name='gwbank_date',
            field=models.CharField(help_text='입출금 날자', max_length=40, verbose_name='날자'),
        ),
    ]
