# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_site', '0003_auto_20180309_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwbank',
            name='gwbank_date',
            field=models.DateField(help_text='입출금 날자', verbose_name='날자'),
        ),
    ]
