# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_site', '0007_auto_20180310_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwbank',
            name='gwbank_execution',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='특정 값 합계 금액 적는 필드', verbose_name='특정 값 합계 금액 정수'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gwbank',
            name='gwbank_note',
            field=models.CharField(blank=True, default=0, help_text='메모 필드', max_length=200, verbose_name='메모'),
        ),
    ]
