# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_site', '0008_auto_20180310_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwbank',
            name='gwbank_execution',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='특정 값 합계 금액 적는 필드', null=True, verbose_name='특정 값 합계 금액 정수'),
        ),
    ]
