# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_site', '0014_auto_20180310_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwbank',
            name='gwbank_note',
            field=models.CharField(blank=True, default=0, help_text='메모 필드', max_length=200, verbose_name='메모'),
        ),
    ]
