# Generated by Django 3.1 on 2020-08-12 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family_site', '0016_auto_20200812_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(help_text='  ', max_length=200, verbose_name='제목')),
                ('note_content', models.TextField(verbose_name='내용 (사진 사이즈가 크면 등록되지 않습니다!)')),
                ('note_created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='생성 날자', verbose_name='생성일')),
                ('note_published_date', models.DateTimeField(auto_now=True, help_text='글 수정 일시', null=True, verbose_name='수정일')),
                ('note_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NoteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notecomment_content', models.TextField(verbose_name='글내용')),
                ('notecomment_created_date', models.DateTimeField(auto_now_add=True, help_text='생성날자', verbose_name='생성날자')),
                ('notecomment_publish_date', models.DateTimeField(auto_now=True, help_text='수정날자', verbose_name='수정날자')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='family_site.note')),
                ('notecomment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-notecomment_created_date',),
            },
        ),
    ]
